# $NetBSD$

DISTNAME=	sg3_utils-1.48
PKGNAME=	${DISTNAME:S/_/-/}
CATEGORIES=	extra
MASTER_SITES=	https://sg.danny.cz/sg/p/
EXTRACT_SUFX=	.tgz

MAINTAINER=	jperkin@pkgsrc.org
HOMEPAGE=	https://sg.danny.cz/sg/
COMMENT=	Collection of SCSI utilities
LICENSE=	2-clause-bsd

GNU_CONFIGURE=	yes
USE_LANGUAGES=	c
USE_LIBTOOL=	yes

.include "../../mk/bsd.pkg.mk"
